import { GOOGLE, PINTEREST, TUMBLR } from "../pageobjects/utils/constant";

// constants.js
export const FEED_PATH = {
  INSTAGRAM: (wallId) => `/content/addfeed/${wallId}/18`,
  LINKEDIN: (wallId) => `/content/addfeed/${wallId}/10`,
  GOOGLE: (wallId) => `/content/addfeed/${wallId}/4`,
  YOUTUBE: (wallId) => `/content/addfeed/${wallId}/7`,
  TIKTOK: (wallId) => `/content/addfeed/${wallId}/28`,
  PINTEREST: (wallId) => `/content/addfeed/${wallId}/5`,
  VIMEO: (wallId) => `/content/addfeed/${wallId}/8`,
  FLICKR: (wallId) => `/content/addfeed/${wallId}/6`,
  TUMBLR: (wallId) => `/content/addfeed/${wallId}/11`,
  YELP: (wallId) => `/content/addfeed/${wallId}/19`,
  AIRBNB: (wallId) => `/content/addfeed/${wallId}/23`,
  TRIPADVISOR: (wallId) => `/content/addfeed/${wallId}/35`,
  AMAZON: (wallId) => `/content/addfeed/${wallId}/34`,
  ALIEXPRESS: (wallId) => `/content/addfeed/${wallId}/37`,
  BOOKINGCOM: (wallId) => `/content/addfeed/${wallId}/38`,
  RSS: (wallId) => `/content/addfeed/${wallId}/12`,
  SLACK: (wallId) => `/content/addfeed/${wallId}/20`,
  UPLOAD: (wallId) => `/content/addfeed/${wallId}`,
  REQUESTNETWORK: (wallId) => `/content/addfeed/${wallId}`,
  TWITTER: (wallId) => `/content/addfeed/${wallId}/1`,
  FACEBOOK: (wallId) => `/content/addfeed/${wallId}/3`,
  REVIEWHUB: (wallId) => `/content/addfeed/${wallId}/29`,
  REDDIT: (wallId) => `/content/addfeed/${wallId}/47`,
  MODERATION: (wallId) => `/content/moderation/${wallId}/`,
  AUTOPILOT: `/autopilot/`,
  PUBLISH: `/publish`,
  PRODUCT_CATALOG_URL: '/content/products',
  PROFILE_URL: '/profile',
  PRICE_URL: '/transactions',
  LOGIN_URL: '/accounts/login',
  DASHBOARD_URL: '/home',
};